---
language: ruby
sudo: false
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
notifications:
  email: false
env:
  - PUPPET_GEM_VERSION="~> 3.7.0"
  - PUPPET_GEM_VERSION="~> 3.8.0"
  - PUPPET_GEM_VERSION="~> 4.1.0"
  - PUPPET_GEM_VERSION="~> 4.2.0"
script:
  - puppet --version
  - bundle exec rake validate lint spec
matrix:
  include:
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.7.0" RSPEC_GEM_VERSION="< 3.2.0"
    - rvm: 1.8.7
      env: PUPPET_GEM_VERSION="~> 3.8.0" RSPEC_GEM_VERSION="< 3.2.0"
  exclude:
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.7.0"
    - rvm: 2.2
      env: PUPPET_GEM_VERSION="~> 3.8.0"
